---
title: "Aimi stuff"
format: pdf
editor: visual
---

```{r}
men_country = c("CHN", "JPN", "GBR", "USA", "CAN", "GER", "ITA", "SUI", "ESP", "TUR", "NED", "UKR")
```

```{r}

# create a group of elite athletes who have done well in major competitions within the last two years.

# We are filtering for athletes that have made it within the top 10 in any event in world competitions.
world_elites <- df_men_c %>%
  filter(competition_scope == "World")%>%
  filter(Round != "TeamFinal")%>%
  filter(Round != "TeamQual")%>%
  filter(Rank != 0) %>%
  filter(Rank <= 10)%>%
  distinct(clean_name, clean_country)

# And filtering for any athletes who have placed within top 3 in other competitions.
# for some extraneous reasons, some high level athletes may have chosen not to compete 
# in any world competitions within the last two years.
other_elites <- df_men_c %>%
  filter(competition_scope != "World")%>%
  filter(Round != "TeamFinal")%>%
  filter(Round != "TeamQual")%>%
  filter(Rank != 0) %>%
  filter(Rank <= 3)%>%
  distinct(clean_name, clean_country)

# we join together these two groups to form a group of all the elite athletes
all_elites_m <- full_join(world_elites, other_elites, by = c("clean_name", "clean_country"))


```

```{r}
# sanity check to look at how many elite athletes from USA / which athletes
all_elites_m%>%
  filter(clean_country == "USA")

# sanity check to look at how many elite athletes from each country
all_elites_m%>%
  group_by(clean_country)%>%
  count()%>%
  filter(n>=5)%>%
  arrange(desc(n))
```

```{r}
# Create a function to simulate a score for a given athlete and given event
# based off of the athlete's previous scores on the event within the last two yrs. 

simulate_score_m <- function(athlete, event) {
  
  # filter to get all past data of athlete on this event
  athlete_data <- df_men_c%>%
    filter(clean_name == athlete, Apparatus == event)
  
  # if the athlete has no past data, the score is 0
  if(nrow(athlete_data)==0){
    score = 0
    return(score)
  
  # if athlete only has one datapoint to reference, we will create a small normal
  # around this point and sample directly.
  }else if (nrow(athlete_data)==1){
    poss_scores <- rnorm(n = 30, mean = athlete_data$Score, sd = 0.1)
    score = sample(poss_scores, size = 1)
    return(score)
    
  # also if athlete scores are multiple identical scores
  }else if (all(athlete_data$Score == athlete_data$Score[1])){
    poss_scores <- rnorm(n = 30, mean = athlete_data$Score[1], sd = 0.1)
    score = sample(poss_scores, size = 1)
    return(score)
    
      
   # else get string of scores and create a kernel density estimate of pdf   
  } else{
    scores <- athlete_data$Score
    
    # density function takes on default of gaussian kernel and default bandwidth
    density_estimate = density(scores)
    
    # we sample one point from the estimated kernel density pdf
    score <- sample(density_estimate$x, size = 1, prob = density_estimate$y)
    return(score)
  }
}
```

```{r}
#Sanity Check for when he doesn't have an event
simulate_score_w("Alex DIAB", "VT2")
```

```{r}
#Sanity Check
simulate_score_m("Daiki HASHIMOTO", "HB")
```

```{r}
median_of_kernel_m <- function(athlete, event) {
  
  # filter to get all past data of athlete on this event
  athlete_data <- df_men_c%>%
    filter(clean_name == athlete, Apparatus == event)
  
  # if the athlete has no past data, the median score is 0
  if(nrow(athlete_data)==0){
    median_score = 0
    return(median_score)
    
  # if athlete only has one datapoint to reference, that is used as median
  }else if (nrow(athlete_data)==1){
    median_score <- athlete_data$Score
    return(median_score)  
  }else if (all(athlete_data$Score == athlete_data$Score[1])){
    median_score <- athlete_data$Score[1] 
    return(median_score)  
      
  # else get string of scores and create a kernel density estimate of pdf
  } else{
    scores <- athlete_data$Score
    
    # density function takes on default of gaussian kernel and default bandwidth
    density_estimate = density(scores)
    
    # we want to get the median of the pdf
    # first create the cdf
    cdf <- cumsum(density_estimate$y) * diff(density_estimate$x[1:2])

    # Find the index where the CDF is closest to 0.5
    median_index <- which.min(abs(cumsum(cdf) - 0.5))
    
    # Extract the median value from the x-values
    median_score <- density_estimate$x[median_index]

    return(median_score)
  }
}
```

```{r}
# for a certain event (or individual AA / individual vault need to sum up events) 
# and a certain set of athletes return the winners data set
# (note winners cannot all be from same country, max 2 from same country)

set.seed(21)

# function takes event, a dataset of athletes, (and if necessary,  a country filter)
# country filter is to make this a multi-use function later on to select best 3 athletes
# a country may use for a event in the all around competition

event_sim_indiv_m <- function(event_set, dataset = all_elites_m, country = NA){
  
  all_elites_event <- dataset
  
  # if country filter
  # if (is.na(country) == FALSE){
  #   all_elites_event <- all_elites_event %>%
  #     filter(clean_country == country)
  # }
  
  # for each event, simulate athletes performances
  for (event in event_set){
    
    # create a vector of the athletes performances in this event
    all_points = c()
    for (athlete in all_elites_event$clean_name){
      points <- simulate_score_m(athlete, event)
      all_points <- c(all_points, points)
    }
    
    # attaching to the original dataset the simulated performances
    col_name <- paste("event_", event, sep= "")
    all_elites_event[, col_name] <- all_points
    
  }
  
  # summing up the scores across the events to determine winners
  columns_to_exclude <- c("clean_name", "clean_country")
  all_elites_event$sum_score <- rowSums(all_elites_event[, !names(all_elites_event) %in% columns_to_exclude])
  winners <- all_elites_event%>%
    arrange(desc(sum_score))%>%
    slice(1:3)
  
  # we cannot have all three winners be from the same country as per rules of world competitions
  # check if all winners are from same country, if yes, get the 4th highest score.
  all_same <- all(winners$clean_country == winners$clean_country[1])
  # all_same <- TRUE
  if (all_same){
    winners <- all_elites_event%>%
    arrange(desc(sum_score))%>%
    slice(1:2, 4)
  }
  
  medal_count <- c(3,2,1)
  winners <- cbind(winners, medal_count)
  return(winners)
  
}
```

```{r}
event_sim_indiv_m(c("VT1", "VT2"), all_elites)
```

```{r}
# if the athlete is not in one of the countries that already qualified, they are
# filed as having the country "Other" and will compete in individual events 
# but not in the team events. 

all_elites_mc <- all_elites_m 

all_elites_mc$clean_country <- ifelse(all_elites_mc$clean_country %in% men_country, 
                                     all_elites_mc$clean_country, 
                                     "Other")

# Sanity check, look at all the the country assignations
all_elites_mc%>%
  group_by(clean_country) %>%
  count()%>%
  arrange(desc(n))
```

```{r}
# Randomly sampling five athletes per country for the teams

get_teams <- function(data = all_elites_mc){
  all_elites_teams <- data %>%
  filter(clean_country != "Other") %>%
  group_by(clean_country) %>%
  sample_n(5) %>%
  ungroup()
  return(all_elites_teams)
}
  
teams <- get_teams(all_elites_mc)
```

```{r}
set.seed(21)

# For a given event and set of athletes and country select the predicted winners 
# Used to select the three best athletes for each event out of a 5 person team

event_sim_team_m <- function(event, dataset = all_elites, country){
  all_elites_event <- dataset

  all_elites_event <- all_elites_event %>%
    filter(clean_country == country)
  
  all_points = c()
  for (athlete in all_elites_event$clean_name){
    points <- simulate_score_m(athlete, event)
    all_points <- c(all_points, points)
  }
  col_name <- "sum_score"
  all_elites_event[, col_name] <- all_points
    

  winners <- all_elites_event%>%
    arrange(desc(sum_score))%>%
    slice(1:3)
  
  all_same <- all(winners$clean_country == winners$clean_country[1])
  all_same <- TRUE
  if (all_same){
    winners <- all_elites_event%>%
    arrange(desc(sum_score))%>%
    slice(1:2, 4)
  }
  
  winners$apparatus <- rep(event, nrow(winners))
  return(winners)
  
}

# sanity check
event_sim_team("PH", teams, "USA")
```
```{r}
apparatuses_m = c("VT", "SR", "PH", "PB", "HB", "FX")
```

```{r}
top_athletes_m <- data.frame(clean_country = character(),apparatus = character(), clean_name = character(), sum_score = numeric())
```

```{r}
for (country in men_country) {
  for (apparatus in apparatuses_m){
    top3 <- event_sim_team(apparatus, teams, country)
    top_athletes_m <- rbind(top_athletes_m, top3)
  }
 
}

```

```{r}
top_athletes_m
```

```{r}
set.seed(21)
event_sim_m <- function(event, dataset = all_elites){
  all_elites_event <- dataset
  
  all_points = c()
  for (athlete in all_elites_event$clean_name){
    points <- simulate_score_m(athlete, event)
    all_points <- c(all_points, points)
  }
  col_name <- "sum_score"
  all_elites_event[, col_name] <- all_points
  return(all_elites_event)
  
}
```


```{r}

total_scores <- data.frame(clean_country = character(), sum_score = numeric())
#print(total_scores)



for (app in apparatuses_m){
  
  subset <- top_athletes_m[top_athletes_m$apparatus == app,] %>%
    select(-c(sum_score))
  #print(subset)
  
  event_df <- event_sim(app, subset)
  #print(event_df)
  
  total_scores <- rbind(total_scores, event_df)

}

total_scores %>% 
  group_by(clean_country) %>%
  mutate(final_scores = sum(sum_score))%>%
  distinct(clean_country, final_scores)%>%
  arrange(desc(final_scores))

```
