---
title: "simulation_analysis"
output: pdf_document
date: "2023-11-01"
---

```{r}
library(knitr)
```

```{r}

women_sims <- readRDS("~/gym2024data/simulations_Aimi.rds")
men_sims <- readRDS("~/gym2024data/simulations_m_katie.rds")

women_sims2 <- readRDS("~/gym2024data/simulations_seed7.rds")

women_sims3 <- readRDS("~/gym2024data/simulations_Aimi_seed5.rds")

```

```{r}

men_sims_for_second = men_sims[-1]

max_medals = -1
max_sim_index = -1

for (i in seq_along(men_sims_for_second)){
  summaryTeam <- men_sims_for_second[[i]]@teamSummary
  USA_medals <- summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
  
  if (USA_medals>max_medals){
    max_medals <- USA_medals
    max_sim_index <- i
  }
}

second_USA_sim <- men_sims_for_second[[max_sim_index]]@teamSummary
print(second_USA_sim$athletes[second_USA_sim$clean_country == "USA"])

```

```{r}
# top US simulations for men

USA_medals_m <- vector("list", length = 5000)

for (i in seq_along(USA_medals_m)) {
  summaryTeam <- men_sims[[i]]@teamSummary
  USA_medals_m[i] <- summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

USA_medals_m = unlist(USA_medals_m)

top_indices <- order(USA_medals_m, decreasing = TRUE)[1:10]
top_indices

write_rds(top_indices, file = "men_indices.rds")

```

```{r}
first_medals_m <- men_sims[[779]]@teamSummary
first_team_usa_m <- first_medals_m$athletes[first_medals_m$clean_country == "USA"]
first_team_usa_m <- unlist(first_team_usa_m)
```


```{r}
first_team_usa_m
```
```{r}
men_usa <- df_men_c[df_men_c$clean_name %in% first_team_usa_m, c("clean_name", "clean_country")] %>%
  distinct(clean_name, clean_country)
```


```{r}

# top US simulations for women

USA_medals_w <- vector("list", length = 5000)

for (i in seq_along(USA_medals_w)) {
  summaryTeam <- women_sims[[i]]@teamSummary
  USA_medals_w[i] <- summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

USA_medals_w = unlist(USA_medals_w)

top_indices <- order(USA_medals_w, decreasing = TRUE)[1:10]
top_indices

write_rds(top_indices, file = "women_indices.rds")

```

```{r}

first_medals_w <- women_sims[[3864]]@teamSummary
first_team_usa_w <- first_medals_w$athletes[first_medals_w$clean_country == "USA"]
first_medals_w
```



```{=latex}

\newcommand{\highlight}[1]{\colorbox{yellow}{#1}}

\begin{table}[htbp]
  \caption{Men's Artistic Gymnastics - Best Simulated Outcome for Team USA}
  \medskip
  \small
  \begin{tabular}{l|l|l|l}
    \multicolumn{1}{c}{\textbf{Event}} & \multicolumn{1}{c}{\textbf{Gold}} & \multicolumn{1}{c}{\textbf{Silver}} & \multicolumn{1}{c}{\textbf{Bronze}} \\
    \hline
    Team All-Around & \highlight{USA} & China & Switzerland \\
    \hline
    Individual All-Around & \highlight{USA (Brody Malone)} & China (Boheng Zhang) & China (Wei Sun) \\
    \hline
    Vault & Armenia (Artur Davtyan) & Philippines (Carlos Yulo) & Great Britain (Luke Whitehouse) \\
    \hline
    Still Rings & \highlight{USA (Javier Alfonso)} & \highlight{USA (Brody Malone)} & Italy (Salvatore Maresca) \\
    \hline
    Pommel Horse & Chinese Taipei (Chih Lee) & Kazakhstan (Nariman Kurbanov) & Uzbekistan (Abdulla Azimov) \\
    \hline
    Parallel Bars & China (Jingyuan Zou) & \highlight{USA (Curran Phillips)} & Switzerland (Noe Seifert) \\
     \hline
    High Bar & \highlight{USA (Frederick Richard)} & Kazakhstan (Ilyas Azizov) & \highlight{USA (Brody Malone)} \\
    \hline
    Floor Exercise & \highlight{USA (Brody Malone)} & Israel (Artem Dolgopyat) & India (Satyajit Mondal) \\

  \end{tabular}
  
  \label{tab:gymnastics_medals}
\end{table}

  \small
  \textbf{Team USA Athletes: Brody Malone, Javier Alfonso, Curran Phillips, Frederick Richard, Joshua Karnes} \\
  \textbf{Team USA Medal Count:} 8 \\
  \textbf{Team USA Weighted Medal Count:} 20 (where Gold = 3, Silver = 2, Bronze = 1) \\
  \textbf{Team USA Medal Breakdown:} 5 Gold, 2 Silver, 1 Bronze
```


```{=latex}

\begin{table}[htbp]
  \caption{Women's Artistic Gymnastics - Best Simulated Outcome for Team USA}
  \medskip
  \small
  \begin{tabular}{l|l|l|l}
    \multicolumn{1}{c}{\textbf{Event}} & \multicolumn{1}{c}{\textbf{Gold}} & \multicolumn{1}{c}{\textbf{Silver}} & \multicolumn{1}{c}{\textbf{Bronze}} \\
    \hline
    Team All-Around & \highlight{USA} & Brazil & China \\
    \hline
    Individual All-Around & \highlight{USA (Simone Biles)} & Brazil (Rebeca Andrade) & \highlight{USA (Konnor McClain)} \\
    \hline
    Balance Beam & \highlight{USA (Konnor McClain)} & \highlight{USA (Simone Biles)} & China (Qingying Zhang) \\
    \hline
    Vault & \highlight{USA (Jade Carey)} & \highlight{USA (Simone Biles)} & South Korea (Seojeong Yeo) \\
    \hline
    Floor Exercise & \highlight{USA (Simone Biles)} & \highlight{USA (Jade Carey)} & Brazil (Rebeca Andrade) \\
    \hline
    Uneven Bars & Algeria (Kaylia Nemour) & Russia (Viktoria Listunova) & \highlight{USA (Shilese Jones)} \\

  \end{tabular}
  
  \label{tab:gymnastics_medals}
\end{table}

  \small
  \textbf{Team USA Athletes: Simone Biles, Shilese Jones, Karis German, Konnor McClain, Jade Carey} \\
  \textbf{Team USA Medal Count:} 10 \\
  \textbf{Team USA Weighted Medal Count:} 23 (where Gold = 3, Silver = 2, Bronze = 1) \\
  \textbf{Team USA Medal Breakdown:} 5 Gold, 3 Silver, 2 Bronze
```


```{r}
set.seed(42)
data <- data.frame(
  x = rep(1:5, each = 2),
  y = rnorm(10),
  group = rep(c("Group A", "Group B"), times = 5)
)

# Plot before changing legend labels
library(ggplot2)
p_before <- ggplot(data, aes(x = x, y = y, color = group)) +
  geom_point() +
  labs(title = "Scatter Plot (Before)", x = "X-axis", y = "Y-axis") +
  theme_minimal()

# Show plot before changing legend labels
print(p_before)

# Change legend labels
p_after <- p_before + scale_color_manual(values = c("Group A" = "red", "Group B" = "blue"),
                        labels = c("New Label A", "New Label B"))

# Show plot after changing legend labels
print(p_after)
```



Looking at the second iteration of Women's Teams:

```{r}

top_women_team_sim1 <- readRDS("part2_women_team_sim1.rds")
top_women_team_sim2 <- readRDS("part2_women_team_sim2.rds")
top_women_team_sim3 <- readRDS("part2_women_team_sim3.rds")
```



For Team 1:
```{r}
winning_countries <- c()

for (i in seq_along(top_women_team_sim1)){
  team_summary <- top_women_team_sim1[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```


```{r}
country_counts <- table(winning_countries)
country_counts
```


For Team 2:
```{r}
winning_countries <- c()

for (i in seq_along(top_women_team_sim2)){
  team_summary <- top_women_team_sim2[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```


For Team 3:
```{r}
winning_countries <- c()

for (i in seq_along(top_women_team_sim3)){
  team_summary <- top_women_team_sim3[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

```{r}
# avg total medals for team combination 1
top_team_1_totals = 0

for (i in seq_along(top_women_team_sim1)) {
  summaryTeam <- top_women_team_sim1[[i]]@teamSummary
  top_team_1_totals = top_team_1_totals + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team1 = top_team_1_totals / 300
avg_total_medals_team1

```

```{r}
# avg total medals for team combination 2
top_team_2_totals = 0

for (i in seq_along(top_women_team_sim2)) {
  summaryTeam <- top_women_team_sim2[[i]]@teamSummary
  top_team_2_totals = top_team_2_totals + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team2 = top_team_2_totals / 300
avg_total_medals_team2

```

```{r}
# avg total medals for team combination 3
top_team_3_totals = 0

for (i in seq_along(top_women_team_sim3)) {
  summaryTeam <- top_women_team_sim3[[i]]@teamSummary
  top_team_3_totals = top_team_3_totals + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team3 = top_team_3_totals / 300
avg_total_medals_team3

```

Team 3 had the highest average weighted medal count for all 300 simulations. We will choose them as our Team USA.

