---
title: "Main"
author: "Katie"
date: "2023-10-30"
output: 
  html_document:
    fig_caption: yes
---
```{r lineplot-of-points-women}

library(tidyverse)
library(ggsci)

US_women <- filter(df_women_c, Country == "USA")


ggplot(data = US_women, aes(y= FirstName, x = Rank))+
  geom_boxplot()+
  theme_minimal()+
  labs(
    title = "Range of Rank at all competitions",
    subtitle = "For US Women",
    x = "Rank",
    y = "Name"
  )


```

#difference between difficulty in qualifying vs. final rounds
- use to determine whether or not to include quali in final rounds

```{r diff-quali-v-final-vis}

ggplot(data = df_women_c, aes(y = D_Score, color = Round))+
  geom_boxplot()+
  facet_wrap(.~Apparatus)


```

```{r diff-world-v-nonworld-vis}

ggplot(data = df_women_c, aes(y = D_Score, color = competition_scope))+
  geom_boxplot()+
  facet_wrap(.~Apparatus)
```

```{r Score-world-v-nonworld-vis}

ggplot(data = df_women_c, aes(y = Score, fill = competition_scope))+
  geom_boxplot()+
  facet_wrap(.~Apparatus)+
  theme_minimal()+scale_fill_aaas()+
  labs(
    title = 
  )
```

```{r}
par(mar = c(1, 3.5, 1, 1))
barplot(1:10, col = pal_aaas()(10))
```


