---
title: "check_men_gymnastics"
format: pdf
editor: visual
---

## Setting up the Environment

```{r}
setClass(
  "GymnasticSimulation",
  representation(
    teamSummary = "data.frame",
    teamAllAround = "data.frame",
    indivAllAround = "data.frame",
    VT = "data.frame",
    SR = "data.frame",
    PH = "data.frame", 
    PB = "data.frame", 
    HB = "data.frame",
    FX = "data.frame"
  )
)

# Create a constructor function
GymnasticSimulation <- function(teamSummary = data.frame(),
                                teamAllAround = data.frame(),
                                indivAllAround = data.frame(),
                                VT = data.frame(),
                                SR = data.frame(),
                                PH = data.frame(), 
                                PB = data.frame(), 
                                HB = data.frame(),
                                FX = data.frame()
                              
                                 ) {
  new("GymnasticSimulation",
      teamSummary = teamSummary,
      teamAllAround = teamAllAround,
      indivAllAround = indivAllAround,
      VT = VT,
      SR = SR,
      PH = PH,
      PB = PB, 
      HB = HB, 
      FX = FX)
}
```

## Team 1

```{r}
men_team_sim1 <- readRDS("men_team_sim1.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim1)){
  team_summary <- men_team_sim1[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

## Men 2

```{r}
men_team_sim2 <- readRDS("men_team_sim2.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim2)){
  team_summary <- men_team_sim2[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

## Team 3

```{r}
men_team_sim3 <- readRDS("men_team_sim3.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim3)){
  team_summary <- men_team_sim3[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

##Team 4

```{r}
men_team_sim4 <- readRDS("men_team_sim4.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim4)){
  team_summary <- men_team_sim4[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

##Team 5

```{r}
men_team_sim5 <- readRDS("men_team_sim5.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim5)){
  team_summary <- men_team_sim5[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

##Team 6

```{r}
men_team_sim6 <- readRDS("men_team_sim6.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim6)){
  team_summary <- men_team_sim6[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

##Team 7

```{r}
men_team_sim7 <- readRDS("men_team_sim7.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim7)){
  team_summary <- men_team_sim7[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

##Team 8

```{r}
men_team_sim8 <- readRDS("men_team_sim8.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim8)){
  team_summary <- men_team_sim8[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

##Team 9

```{r}
men_team_sim9 <- readRDS("men_team_sim9.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim9)){
  team_summary <- men_team_sim9[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

##Team10

```{r}
men_team_sim10 <- readRDS("men_team_sim10.rds")
```

```{r}
winning_countries <- c()

for (i in seq_along(men_team_sim10)){
  team_summary <- men_team_sim10[[i]]@teamSummary
  
  top_countries <- team_summary %>%
    arrange(desc(total_medals))
  
  winning_country = top_countries$clean_country[1]
  
  if(winning_country == "Other"){
    winning_country = top_countries$clean_country[2]
  }
  
  
  winning_countries <- c(winning_countries, winning_country)
}
```

```{r}
country_counts <- table(winning_countries)
country_counts
```

## Analyzing the winning team: Team 7

```{r}
team_summary <- men_team_sim7[[1]]@teamSummary

winning_men_team <- team_summary$athletes[team_summary$clean_country == "USA"]

winning_men_team
```

```{r}
# finding top performance within men_team_sim7

top_team_USA_medals_m <- vector("list", length = 300)

for (i in seq_along(top_team_USA_medals_m)) {
  summaryTeam <- men_team_sim7[[i]]@teamSummary
  top_team_USA_medals_m[i] <- summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

top_team_USA_medals_m = unlist(top_team_USA_medals_m)

topteam_and_indices_m <- order(top_team_USA_medals_m, decreasing = TRUE)[1]
topteam_and_indices_m

```

```{r}
first_medal_m <- men_team_sim7[[252]]@teamSummary
```

```{r}
aggregated_heatmap_data_men <- data.frame(Country = character(), Event = character(), Medals = numeric(), stringsAsFactors = FALSE)

# Loop through simulations
for (i in seq_along(men_team_sim7)) {
  # Access the team_summary_dataframe from the current simulation
  team_summary <- men_team_sim7[[i]]@teamSummary
  
  # Identify individual event columns (assuming they have the "_Medal" suffix)
  event_columns <- grep("_medal$", names(team_summary), value = TRUE)
  
  # Aggregate medals across events for each country in the current simulation
  aggregated_data <- aggregate(team_summary[, c(event_columns, "total_medals")], by = list(Country = team_summary$clean_country), sum)
  
  # Append the aggregated data to the overall data frame
  aggregated_heatmap_data_men <- rbind(aggregated_heatmap_data_men, aggregated_data)
}
```

```{r}
long_format_data_men <- aggregated_heatmap_data_men %>%
  select(-c("total_medals")) %>%
  gather(key = "Event", value = "Medals", -Country)

long_format_data_men <- long_format_data_men %>%
  group_by(Country, Event) %>%
  summarise(Medals = mean(Medals, na.rm = TRUE)) %>%
  ungroup()

write_rds(long_format_data_men, "Heatmap_data_men")
```

```{r}
long_format_data_men = read_rds("Heatmap_data_men")
ggplot(long_format_data_men, aes(x = Country, y = Event, fill = Medals)) +
  geom_tile() +
   scale_fill_gradient(low = "darkblue", high = "gold", limits = c(0, max(long_format_data_men$Medals))) +
  labs(title = "Average Country Performance Across Events",
       x = "Country",
       y = "Event",
       fill = "Medals") +
  theme_minimal()
```

### Finding Average Weighted Medal Count for Top Teams

Loading in Top Men's Teams

```{r}

top_men_team_1 <- readRDS("men_team_sim1.rds")
top_men_team_2 <- readRDS("men_team_sim2.rds")
top_men_team_3 <- readRDS("men_team_sim3.rds")
top_men_team_4 <- readRDS("men_team_sim4.rds")
top_men_team_5 <- readRDS("men_team_sim5.rds")
top_men_team_6 <- readRDS("men_team_sim6.rds")
top_men_team_7 <- readRDS("men_team_sim7.rds")
top_men_team_8 <- readRDS("men_team_sim8.rds")
top_men_team_9 <- readRDS("men_team_sim9.rds")
top_men_team_10 <- readRDS("men_team_sim10.rds")
```

```{r}

# avg total medals for team combination 1
top_team_1_totals_m = 0

for (i in seq_along(top_men_team_1)) {
  summaryTeam <- top_men_team_1[[i]]@teamSummary
  top_team_1_totals_m = top_team_1_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team1_m = top_team_1_totals_m / 300
avg_total_medals_team1_m

```

```{r}
top_team_2_totals_m = 0

for (i in seq_along(top_men_team_2)) {
  summaryTeam <- top_men_team_2[[i]]@teamSummary
  top_team_2_totals_m = top_team_2_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team2_m = top_team_2_totals_m / 300
avg_total_medals_team2_m

```

```{r}

top_team_3_totals_m = 0

for (i in seq_along(top_men_team_3)) {
  summaryTeam <- top_men_team_3[[i]]@teamSummary
  top_team_3_totals_m = top_team_3_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team3_m = top_team_3_totals_m / 300
avg_total_medals_team3_m

```

```{r}

top_team_4_totals_m = 0

for (i in seq_along(top_men_team_4)) {
  summaryTeam <- top_men_team_4[[i]]@teamSummary
  top_team_4_totals_m = top_team_4_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team4_m = top_team_4_totals_m / 300
avg_total_medals_team4_m

```

```{r}

top_team_5_totals_m = 0

for (i in seq_along(top_men_team_5)) {
  summaryTeam <- top_men_team_5[[i]]@teamSummary
  top_team_5_totals_m = top_team_5_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team5_m = top_team_5_totals_m / 300
avg_total_medals_team5_m

```

```{r}

top_team_6_totals_m = 0

for (i in seq_along(top_men_team_6)) {
  summaryTeam <- top_men_team_6[[i]]@teamSummary
  top_team_6_totals_m = top_team_6_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team6_m = top_team_6_totals_m / 300
avg_total_medals_team6_m

```

```{r}

top_team_7_totals_m = 0

for (i in seq_along(top_men_team_7)) {
  summaryTeam <- top_men_team_7[[i]]@teamSummary
  top_team_7_totals_m = top_team_7_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team7_m = top_team_7_totals_m / 300
avg_total_medals_team7_m

```

```{r}

top_team_8_totals_m = 0

for (i in seq_along(top_men_team_8)) {
  summaryTeam <- top_men_team_8[[i]]@teamSummary
  top_team_8_totals_m = top_team_8_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team8_m = top_team_8_totals_m / 300
avg_total_medals_team8_m

```

```{r}

# avg total medals for team combination 1
top_team_9_totals_m = 0

for (i in seq_along(top_men_team_9)) {
  summaryTeam <- top_men_team_9[[i]]@teamSummary
  top_team_9_totals_m = top_team_9_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team9_m = top_team_9_totals_m / 300
avg_total_medals_team9_m

```

```{r}

# avg total medals for team combination 1
top_team_10_totals_m = 0

for (i in seq_along(top_men_team_10)) {
  summaryTeam <- top_men_team_10[[i]]@teamSummary
  top_team_10_totals_m = top_team_10_totals_m + summaryTeam$total_medals[summaryTeam$clean_country == "USA"]
}

avg_total_medals_team10_m = top_team_10_totals_m / 300
avg_total_medals_team10_m

```
